name: Build WPR Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download submodules
        run: git submodule update --init --recursive

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r21e

      - name: Install Ninja
        run: choco install ninja -y

      - name: Verify Ninja
        shell: cmd
        run: ninja --version

      - name: Build libraries
        shell: cmd
        run: |
          set ANDROID_TOOLCHAIN=%ANDROID_NDK_ROOT%\build\cmake\android.toolchain.cmake
          .\build.bat

      - name: List output files
        run: find Source/Build -name "*.so"

      - name: Upload .so
        uses: actions/upload-artifact@v4
        with:
          name: android-so
          path: Source/Build/**/*.so
